# Generated by Django 5.0.2 on 2024-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetallocation',
            old_name='daily_change_PLN',
            new_name='daily_change_XXX',
        ),
        migrations.RenameField(
            model_name='assetallocation',
            old_name='profit_PLN',
            new_name='profit_XXX',
        ),
        migrations.RenameField(
            model_name='assetallocation',
            old_name='rate_of_return_PLN',
            new_name='rate_of_return_XXX',
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=16),
        ),
    ]
