# Generated by Django 5.0.2 on 2024-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_asset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='daily_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='daily_change_XXX',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='dividends',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='participation',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='profit_XXX',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='rate_of_return',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='rate_of_return_XXX',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=16),
        ),
    ]
