# Generated by Django 5.0.2 on 2024-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_assetallocation_average_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetallocation',
            name='daily_change',
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='daily_change_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='daily_change_XXX',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='dividends',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='participation',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='profit_XXX',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='rate_of_return',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='rate_of_return_XXX',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
