# Generated by Django 5.0.2 on 2024-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_assetallocation_daily_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='pocket_name',
            field=models.CharField(default='Nazwa Konta1', max_length=100),
            preserve_default=False,
        ),
    ]
